a=str(input("enter your address:"))
name=str(input("enter your name:"))
housenumber=int(input("enter house number:"))
area=str(input("enter your area:"))
city=str(input("enter your city:"))
pincode=int(input("enter your pin:"))
print(a)
print(name)
print(housenumber)
print(area)
print(city)
print(pincode)